services:
  meilisearch:
    image: getmeili/meilisearch:nightly
    ports:
      - "7700:7700"
    expose:
      - "7700"
    volumes:
      - ./data/ms:/data/ms
    env_file:
      - ./.env
  
  db:
    image: postgres
    ports:
      - "5432:5432"
    expose:
      - "5432"
    volumes:
      - ./data/postgres:/data/postgres
    env_file:
      - ./.env

  docbot:
    build: .
    ports:
      - "8000:8000"
    expose:
      - "8000"
    env_file:
      - ./.env
volumes:
  postgres:
  meilisearch: