services:
  meilisearch:
    image: getmeili/meilisearch:nightly
    ports:
      - "7700:7700"
    expose:
      - "7700"
    environment:
      - MEILI_MASTER_KEY=masterKey
    volumes:
      - ./data/ms:/data/ms
  
  db:
    image: postgres
    ports:
      - "5432:5432"
    expose:
      - "5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=db
    volumes:
      - ./data/postgres:/data/postgres

  docbot:
    build: .
    ports:
      - "8000:8000"
    expose:
      - "8000"
    environment:
      - MEILISEARCH_URL=http://meilisearch:7700

  
  